import 'package:flutter/material.dart';

import 'wainzo_colors.dart';

/// Two faces, used for different jobs.
///
/// Inter is the interface: labels, buttons, metadata, body copy. Instrument
/// Serif is the editorial voice — it is reserved for the AI's own sentences,
/// country names and the figure that leads a screen. Keeping the serif rare is
/// what makes an AI preview read as something written rather than something
/// generated by a feed.
abstract final class WainzoTypography {
  static const String sans = 'Inter';
  static const String serif = 'InstrumentSerif';

  static const TextStyle display = TextStyle(
    fontFamily: serif,
    fontSize: 38,
    height: 1.08,
    letterSpacing: -0.4,
    color: WainzoColors.ink,
  );

  static const TextStyle headline = TextStyle(
    fontFamily: serif,
    fontSize: 28,
    height: 1.15,
    letterSpacing: -0.2,
    color: WainzoColors.ink,
  );

  static const TextStyle headlineSmall = TextStyle(
    fontFamily: serif,
    fontSize: 22,
    height: 1.2,
    color: WainzoColors.ink,
  );

  static const TextStyle title = TextStyle(
    fontFamily: sans,
    fontSize: 18,
    height: 1.3,
    fontWeight: FontWeight.w600,
    letterSpacing: -0.2,
    color: WainzoColors.ink,
  );

  static const TextStyle titleSmall = TextStyle(
    fontFamily: sans,
    fontSize: 15,
    height: 1.3,
    fontWeight: FontWeight.w600,
    color: WainzoColors.ink,
  );

  static const TextStyle body = TextStyle(
    fontFamily: sans,
    fontSize: 15,
    height: 1.5,
    fontWeight: FontWeight.w400,
    color: WainzoColors.ink,
  );

  static const TextStyle bodyMuted = TextStyle(
    fontFamily: sans,
    fontSize: 14.5,
    height: 1.5,
    fontWeight: FontWeight.w400,
    color: WainzoColors.inkMuted,
  );

  static const TextStyle caption = TextStyle(
    fontFamily: sans,
    fontSize: 13,
    height: 1.4,
    fontWeight: FontWeight.w400,
    color: WainzoColors.inkMuted,
  );

  static const TextStyle label = TextStyle(
    fontFamily: sans,
    fontSize: 13,
    height: 1.2,
    fontWeight: FontWeight.w500,
    color: WainzoColors.ink,
  );

  /// Small, wide, uppercase: section markers and field labels. Never for copy.
  static const TextStyle overline = TextStyle(
    fontFamily: sans,
    fontSize: 11,
    height: 1.2,
    fontWeight: FontWeight.w600,
    letterSpacing: 1.1,
    color: WainzoColors.inkFaint,
  );

  static const TextStyle button = TextStyle(
    fontFamily: sans,
    fontSize: 15,
    height: 1.1,
    fontWeight: FontWeight.w600,
    letterSpacing: 0.1,
  );
}
